const sidebars = {
  designSidebar: [{ type: 'autogenerated', dirName: 'design' }],
  membersSidebar: [{ type: 'autogenerated', dirName: 'members' }],
  appSidebar: [{ type: 'autogenerated', dirName: 'app' }],
};

export default sidebars;